import type { Flat } from "./types";

const imgs = {
  living: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
  kitchen: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80",
  bedroom: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80",
  balcony: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80",
  exterior: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80",
  modern: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80",
  villa: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
  lounge: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
  bright: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80",
  cozy: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80",
  clean: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cd00?w=1200&q=80",
  studio: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=1200&q=80",
  open: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=1200&q=80",
  warm: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80",
  river: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1200&q=80",
  garden: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80",
  luxury: "https://images.unsplash.com/photo-1600047509358-9dc75590da30?w=1200&q=80",
  metro: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=1200&q=80",
};

export const SEED_FLATS: Flat[] = [
  {
    id: "flat-001",
    title: "Skyline Residences — 3 BHK Corner Flat",
    description:
      "Spacious corner flat with panoramic city views, twin balconies, and premium modular kitchen. Ideal for families seeking natural light and quiet evenings.",
    price: 12500000,
    location: "Whitefield Main Road",
    city: "Bengaluru",
    area: "Whitefield",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    carpetArea: 1580,
    facing: "East",
    floor: 12,
    totalFloors: 18,
    ageYears: 2,
    furnishing: "Semi-Furnished",
    amenities: ["Clubhouse", "Swimming Pool", "Gym", "Children's Play Area", "24/7 Security", "Power Backup", "Covered Parking", "Landscaped Garden"],
    nearbySchools: [
      { name: "Ryan International School", distance: "1.2 km" },
      { name: "Whitefield Global School", distance: "2.0 km" },
    ],
    nearbyColleges: [
      { name: "Vydehi Institute of Medical Sciences", distance: "3.5 km" },
      { name: "CMR Institute of Technology", distance: "4.1 km" },
    ],
    nearbyHospitals: [
      { name: "Manipal Hospital Whitefield", distance: "2.4 km" },
      { name: "Columbia Asia Hospital", distance: "3.0 km" },
    ],
    nearbyTransport: [
      { name: "Whitefield Metro Station", distance: "1.8 km" },
      { name: "ITPL Bus Terminal", distance: "1.1 km" },
      { name: "Kempegowda Intl. Airport", distance: "38 km" },
    ],
    images: [imgs.living, imgs.kitchen, imgs.bedroom, imgs.balcony],
    status: "available",
    featured: true,
    listedAt: "2026-08-12T10:00:00.000Z",
    updatedAt: "2026-09-10T08:00:00.000Z",
  },
  {
    id: "flat-002",
    title: "Forum Edge — 2 BHK Near 80 Feet Road",
    description:
      "Bright 2 BHK in the heart of Koramangala with balcony seating, modular kitchen, and walkable access to cafes and coworking spaces.",
    price: 11200000,
    location: "5th Block, 80 Feet Road",
    city: "Bengaluru",
    area: "Koramangala",
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    carpetArea: 1120,
    facing: "North",
    floor: 6,
    totalFloors: 12,
    ageYears: 4,
    furnishing: "Fully Furnished",
    amenities: ["Gym", "CCTV", "Power Backup", "Covered Parking", "Lift", "Intercom"],
    nearbySchools: [
      { name: "National Public School", distance: "1.5 km" },
      { name: "Sri Kumaran Children's Home", distance: "2.2 km" },
    ],
    nearbyColleges: [
      { name: "St. John's Medical College", distance: "3.0 km" },
      { name: "Christ University", distance: "4.5 km" },
    ],
    nearbyHospitals: [
      { name: "Apollo Spectra", distance: "1.8 km" },
      { name: "St. John's Hospital", distance: "3.1 km" },
    ],
    nearbyTransport: [
      { name: "Koramangala Bus Depot", distance: "0.8 km" },
      { name: "Sony World Junction", distance: "1.2 km" },
      { name: "Kempegowda Intl. Airport", distance: "42 km" },
    ],
    images: [imgs.modern, imgs.open, imgs.warm],
    status: "available",
    featured: true,
    listedAt: "2026-08-20T09:00:00.000Z",
    updatedAt: "2026-09-12T11:00:00.000Z",
  },
  {
    id: "flat-003",
    title: "100 Feet Retreat — Premium 3 BHK",
    description:
      "Elegant Indiranagar apartment with dual balconies, walk-in wardrobe, and metro connectivity for daily city travel.",
    price: 16800000,
    location: "100 Feet Road",
    city: "Bengaluru",
    area: "Indiranagar",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    carpetArea: 1680,
    facing: "West",
    floor: 9,
    totalFloors: 14,
    ageYears: 3,
    furnishing: "Semi-Furnished",
    amenities: ["Clubhouse", "Gym", "Swimming Pool", "24/7 Security", "Visitor Parking", "Power Backup"],
    nearbySchools: [
      { name: "New Horizon Public School", distance: "1.4 km" },
      { name: "Sophia High School", distance: "2.8 km" },
    ],
    nearbyColleges: [
      { name: "Mount Carmel College", distance: "4.2 km" },
      { name: "Jain University", distance: "3.6 km" },
    ],
    nearbyHospitals: [
      { name: "Manipal Hospital HAL", distance: "2.0 km" },
      { name: "Cloudnine Hospital", distance: "1.1 km" },
    ],
    nearbyTransport: [
      { name: "Indiranagar Metro", distance: "0.6 km" },
      { name: "Halasuru Metro", distance: "2.4 km" },
      { name: "Kempegowda Intl. Airport", distance: "40 km" },
    ],
    images: [imgs.luxury, imgs.bright, imgs.balcony, imgs.kitchen],
    status: "available",
    featured: true,
    listedAt: "2026-09-01T10:00:00.000Z",
    updatedAt: "2026-09-16T09:00:00.000Z",
  },
  {
    id: "flat-004",
    title: "Sector 2 Greens — Family 3 BHK",
    description:
      "Vastu-friendly HSR Layout flat with park-facing balcony, utility room, and a calm society lane.",
    price: 13200000,
    location: "Sector 2, 27th Main",
    city: "Bengaluru",
    area: "HSR Layout",
    bedrooms: 3,
    bathrooms: 2,
    balconies: 2,
    carpetArea: 1490,
    facing: "East",
    floor: 4,
    totalFloors: 10,
    ageYears: 5,
    furnishing: "Semi-Furnished",
    amenities: ["Children's Play Area", "Gym", "CCTV", "Covered Parking", "Power Backup", "Landscaped Garden"],
    nearbySchools: [
      { name: "Cambridge School", distance: "1.0 km" },
      { name: "National Public School HSR", distance: "1.7 km" },
    ],
    nearbyColleges: [
      { name: "Dayananda Sagar College", distance: "5.5 km" },
      { name: "Oxford College", distance: "4.8 km" },
    ],
    nearbyHospitals: [
      { name: "Narayana Multispeciality", distance: "2.3 km" },
      { name: "Greenview Medical Center", distance: "1.5 km" },
    ],
    nearbyTransport: [
      { name: "HSR BDA Complex Bus Stop", distance: "0.5 km" },
      { name: "Silk Board Junction", distance: "3.2 km" },
      { name: "Kempegowda Intl. Airport", distance: "45 km" },
    ],
    images: [imgs.garden, imgs.living, imgs.cozy],
    status: "available",
    featured: false,
    listedAt: "2026-07-15T08:00:00.000Z",
    updatedAt: "2026-09-05T12:00:00.000Z",
  },
  {
    id: "flat-005",
    title: "4th Block Classic — 2 BHK Resale",
    description:
      "Well-kept Jayanagar resale with wooden flooring, upgraded bathrooms, and tree-lined street access.",
    price: 9800000,
    location: "4th Block",
    city: "Bengaluru",
    area: "Jayanagar",
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    carpetArea: 1050,
    facing: "South",
    floor: 3,
    totalFloors: 8,
    ageYears: 9,
    furnishing: "Fully Furnished",
    amenities: ["Lift", "Security", "Parking", "Power Backup", "Intercom"],
    nearbySchools: [
      { name: "MES Kishora Kendra", distance: "1.2 km" },
      { name: "Sri Aurobindo School", distance: "2.0 km" },
    ],
    nearbyColleges: [
      { name: "RV College of Engineering", distance: "6.0 km" },
      { name: "Bangalore University", distance: "5.2 km" },
    ],
    nearbyHospitals: [
      { name: "Sagar Hospitals", distance: "2.4 km" },
      { name: "The Nest Hospital", distance: "1.8 km" },
    ],
    nearbyTransport: [
      { name: "Jayanagar Metro (Purple Line)", distance: "1.6 km" },
      { name: "South End Circle Metro", distance: "2.8 km" },
      { name: "Kempegowda Intl. Airport", distance: "44 km" },
    ],
    images: [imgs.river, imgs.warm, imgs.bedroom],
    status: "available",
    featured: false,
    listedAt: "2026-06-10T11:00:00.000Z",
    updatedAt: "2026-08-28T10:00:00.000Z",
  },
  {
    id: "flat-006",
    title: "Phase 1 Heights — 2 BHK Near Tech Parks",
    description:
      "Practical Electronic City apartment for professionals — efficient layout, covered parking, and short commute to major campuses.",
    price: 7200000,
    location: "Phase 1, Hosur Road",
    city: "Bengaluru",
    area: "Electronic City",
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    carpetArea: 980,
    facing: "North-East",
    floor: 7,
    totalFloors: 15,
    ageYears: 3,
    furnishing: "Unfurnished",
    amenities: ["Gym", "Swimming Pool", "CCTV", "Power Backup", "Covered Parking", "Clubhouse"],
    nearbySchools: [
      { name: "Harvest International School", distance: "2.5 km" },
      { name: "Royale Concorde School", distance: "3.1 km" },
    ],
    nearbyColleges: [
      { name: "IIM Bangalore", distance: "8.0 km" },
      { name: "PES University", distance: "9.5 km" },
    ],
    nearbyHospitals: [
      { name: "Narayana Health City", distance: "4.0 km" },
      { name: "Electronic City Hospital", distance: "1.9 km" },
    ],
    nearbyTransport: [
      { name: "Electronic City Metro", distance: "1.2 km" },
      { name: "BMTC Bus Depot", distance: "0.9 km" },
      { name: "Kempegowda Intl. Airport", distance: "52 km" },
    ],
    images: [imgs.studio, imgs.open, imgs.exterior],
    status: "available",
    featured: false,
    listedAt: "2026-07-28T09:30:00.000Z",
    updatedAt: "2026-09-08T14:00:00.000Z",
  },
  {
    id: "flat-007",
    title: "Lakeview Nest — 3 BHK Hebbal",
    description:
      "North-facing apartment with soft lake breeze, twin sit-outs, and quick Outer Ring Road access.",
    price: 14500000,
    location: "Hebbal Lake Road",
    city: "Bengaluru",
    area: "Hebbal",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    carpetArea: 1620,
    facing: "North",
    floor: 11,
    totalFloors: 20,
    ageYears: 1,
    furnishing: "Semi-Furnished",
    amenities: ["Clubhouse", "Swimming Pool", "Gym", "Jogging Track", "EV Charging", "24/7 Security"],
    nearbySchools: [
      { name: "Trio World Academy", distance: "2.0 km" },
      { name: "Canadian International School", distance: "3.4 km" },
    ],
    nearbyColleges: [
      { name: "MS Ramaiah College", distance: "5.5 km" },
      { name: "Reva University", distance: "7.0 km" },
    ],
    nearbyHospitals: [
      { name: "Aster CMI Hospital", distance: "2.2 km" },
      { name: "Baptist Hospital", distance: "4.8 km" },
    ],
    nearbyTransport: [
      { name: "Hebbal Flyover Junction", distance: "1.0 km" },
      { name: "Manyata Tech Park", distance: "3.5 km" },
      { name: "Kempegowda Intl. Airport", distance: "28 km" },
    ],
    images: [imgs.villa, imgs.lounge, imgs.bright, imgs.balcony],
    status: "under-offer",
    featured: true,
    listedAt: "2026-09-05T08:00:00.000Z",
    updatedAt: "2026-09-17T10:00:00.000Z",
  },
  {
    id: "flat-008",
    title: "Airport Corridor — 2 BHK Yelahanka",
    description:
      "New-age 2 BHK with open kitchen, covered parking, and convenient access toward the airport corridor.",
    price: 8100000,
    location: "Yelahanka New Town",
    city: "Bengaluru",
    area: "Yelahanka",
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    carpetArea: 1080,
    facing: "East",
    floor: 5,
    totalFloors: 12,
    ageYears: 2,
    furnishing: "Semi-Furnished",
    amenities: ["Gym", "Children's Play Area", "CCTV", "Power Backup", "Parking", "Lift"],
    nearbySchools: [
      { name: "National Public School Yelahanka", distance: "1.8 km" },
      { name: "Delhi Public School North", distance: "3.0 km" },
    ],
    nearbyColleges: [
      { name: "Nitte Meenakshi Institute", distance: "4.2 km" },
      { name: "Reva University", distance: "5.0 km" },
    ],
    nearbyHospitals: [
      { name: "Navya Multispeciality", distance: "2.1 km" },
      { name: "Sparsh Hospital", distance: "6.5 km" },
    ],
    nearbyTransport: [
      { name: "Yelahanka Railway Station", distance: "2.4 km" },
      { name: "Yelahanka Bus Stand", distance: "1.3 km" },
      { name: "Kempegowda Intl. Airport", distance: "18 km" },
    ],
    images: [imgs.clean, imgs.metro, imgs.kitchen],
    status: "available",
    featured: false,
    listedAt: "2026-08-02T12:00:00.000Z",
    updatedAt: "2026-09-11T09:00:00.000Z",
  },
  {
    id: "flat-009",
    title: "ORR Vista — 3 BHK Sarjapur Road",
    description:
      "Tall-tower apartment with clubhouse access, EV charging, and strong ORR connectivity for daily commutes.",
    price: 11800000,
    location: "Sarjapur Main Road",
    city: "Bengaluru",
    area: "Sarjapur Road",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    carpetArea: 1550,
    facing: "South-East",
    floor: 14,
    totalFloors: 22,
    ageYears: 0,
    furnishing: "Unfurnished",
    amenities: ["Clubhouse", "Swimming Pool", "Gym", "EV Charging", "Concierge", "Banquet Hall", "24/7 Security"],
    nearbySchools: [
      { name: "Oakridge International", distance: "2.6 km" },
      { name: "Inventure Academy", distance: "4.0 km" },
    ],
    nearbyColleges: [
      { name: "Azim Premji University", distance: "6.5 km" },
      { name: "Christ University Kengeri", distance: "12 km" },
    ],
    nearbyHospitals: [
      { name: "Sakra World Hospital", distance: "5.2 km" },
      { name: "Cloudnine Sarjapur", distance: "2.8 km" },
    ],
    nearbyTransport: [
      { name: "ORR Entrance", distance: "1.5 km" },
      { name: "Wipro Sarjapur Gate", distance: "3.0 km" },
      { name: "Kempegowda Intl. Airport", distance: "48 km" },
    ],
    images: [imgs.exterior, imgs.luxury, imgs.living, imgs.cozy],
    status: "available",
    featured: true,
    listedAt: "2026-09-10T07:00:00.000Z",
    updatedAt: "2026-09-18T08:00:00.000Z",
  },
  {
    id: "flat-010",
    title: "Bridge View — 2 BHK Marathahalli",
    description:
      "Compact yet bright flat near Marathahalli bridge with utility area and easy Outer Ring Road hops.",
    price: 8600000,
    location: "Outer Ring Road",
    city: "Bengaluru",
    area: "Marathahalli",
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    carpetArea: 1020,
    facing: "West",
    floor: 8,
    totalFloors: 16,
    ageYears: 6,
    furnishing: "Fully Furnished",
    amenities: ["Gym", "Pool", "CCTV", "Power Backup", "Covered Parking", "Shopping Arcade"],
    nearbySchools: [
      { name: "VIBGYOR High", distance: "2.2 km" },
      { name: "Gear Innovative School", distance: "3.5 km" },
    ],
    nearbyColleges: [
      { name: "New Horizon College", distance: "4.0 km" },
      { name: "CMRIT", distance: "5.5 km" },
    ],
    nearbyHospitals: [
      { name: "Sakaria Hospital", distance: "1.6 km" },
      { name: "Vydehi Hospital", distance: "6.0 km" },
    ],
    nearbyTransport: [
      { name: "Marathahalli Bridge Bus Stop", distance: "0.4 km" },
      { name: "ORR Kundalahalli Gate", distance: "2.0 km" },
      { name: "Kempegowda Intl. Airport", distance: "40 km" },
    ],
    images: [imgs.metro, imgs.bedroom, imgs.open],
    status: "available",
    featured: false,
    listedAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-09-02T15:00:00.000Z",
  },
  {
    id: "flat-011",
    title: "Phase 6 Comfort — 3 BHK JP Nagar",
    description:
      "South Bengaluru family home with balcony garden boxes, covered parking, and neighbourhood market access.",
    price: 10900000,
    location: "15th Cross, Phase 6",
    city: "Bengaluru",
    area: "JP Nagar",
    bedrooms: 3,
    bathrooms: 2,
    balconies: 2,
    carpetArea: 1400,
    facing: "North-West",
    floor: 2,
    totalFloors: 9,
    ageYears: 7,
    furnishing: "Semi-Furnished",
    amenities: ["Garden", "Community Hall", "Gym", "Parking", "Security", "Power Backup"],
    nearbySchools: [
      { name: "Delhi Public School South", distance: "2.4 km" },
      { name: "National Academy for Learning", distance: "1.9 km" },
    ],
    nearbyColleges: [
      { name: "DSCE", distance: "4.5 km" },
      { name: "BMS College of Engineering", distance: "7.0 km" },
    ],
    nearbyHospitals: [
      { name: "Sagar Hospitals Jayanagar", distance: "3.2 km" },
      { name: "Apollo Clinic JP Nagar", distance: "1.4 km" },
    ],
    nearbyTransport: [
      { name: "JP Nagar Metro", distance: "1.8 km" },
      { name: "Puttenahalli Bus Stop", distance: "0.7 km" },
      { name: "Kempegowda Intl. Airport", distance: "46 km" },
    ],
    images: [imgs.garden, imgs.warm, imgs.kitchen],
    status: "available",
    featured: false,
    listedAt: "2026-05-22T09:00:00.000Z",
    updatedAt: "2026-08-30T11:00:00.000Z",
  },
  {
    id: "flat-012",
    title: "Eco Lake Towers — 3 BHK Bellandur",
    description:
      "Lake-proximate ORR apartment with smart-home ready fittings and strong weekday commute options.",
    price: 13900000,
    location: "Bellandur Outer Ring Road",
    city: "Bengaluru",
    area: "Bellandur",
    bedrooms: 3,
    bathrooms: 3,
    balconies: 2,
    carpetArea: 1600,
    facing: "East",
    floor: 16,
    totalFloors: 24,
    ageYears: 2,
    furnishing: "Semi-Furnished",
    amenities: ["Clubhouse", "Swimming Pool", "Gym", "Smart Home Ready", "EV Charging", "24/7 Security"],
    nearbySchools: [
      { name: "Greenwood High", distance: "3.0 km" },
      { name: "The International School Bangalore", distance: "5.5 km" },
    ],
    nearbyColleges: [
      { name: "Christ University", distance: "8.0 km" },
      { name: "New Horizon College", distance: "4.8 km" },
    ],
    nearbyHospitals: [
      { name: "Sakra World Hospital", distance: "2.5 km" },
      { name: "Cloudnine Bellandur", distance: "1.8 km" },
    ],
    nearbyTransport: [
      { name: "Bellandur Gate Bus Stop", distance: "0.6 km" },
      { name: "ORR Central Silk Board", distance: "5.0 km" },
      { name: "Kempegowda Intl. Airport", distance: "43 km" },
    ],
    images: [imgs.lounge, imgs.balcony, imgs.modern, imgs.clean],
    status: "available",
    featured: false,
    listedAt: "2026-08-25T13:00:00.000Z",
    updatedAt: "2026-09-14T16:00:00.000Z",
  },
  {
    id: "flat-013",
    title: "Lakeview Heights — Premium 2 BHK",
    description:
      "Elegant 2 BHK overlooking the lake promenade. Open living-dining layout with wooden flooring.",
    price: 8900000,
    location: "Hiranandani Gardens",
    city: "Mumbai",
    area: "Powai",
    bedrooms: 2,
    bathrooms: 2,
    balconies: 1,
    carpetArea: 980,
    facing: "North",
    floor: 8,
    totalFloors: 22,
    ageYears: 5,
    furnishing: "Fully Furnished",
    amenities: ["Infinity Pool", "Gym", "Jogging Track", "Indoor Games", "Visitor Parking", "CCTV"],
    nearbySchools: [
      { name: "Podar International School", distance: "0.9 km" },
      { name: "Hiranandani Foundation School", distance: "1.4 km" },
    ],
    nearbyColleges: [
      { name: "IIT Bombay", distance: "3.2 km" },
      { name: "S.M. Shetty College", distance: "2.1 km" },
    ],
    nearbyHospitals: [
      { name: "Hiranandani Hospital", distance: "1.0 km" },
      { name: "Powai Hospital", distance: "2.5 km" },
    ],
    nearbyTransport: [
      { name: "Powai Bus Depot", distance: "0.7 km" },
      { name: "Kanjurmarg Railway Station", distance: "4.5 km" },
      { name: "Chhatrapati Shivaji Airport", distance: "12 km" },
    ],
    images: [imgs.exterior, imgs.modern, imgs.villa],
    status: "available",
    featured: false,
    listedAt: "2026-07-22T09:00:00.000Z",
    updatedAt: "2026-09-05T11:30:00.000Z",
  },
  {
    id: "flat-014",
    title: "Green Grove Towers — Family 4 BHK",
    description:
      "Vastu-compliant 4 BHK with dual-aspect ventilation and private terrace in Gachibowli.",
    price: 18500000,
    location: "Financial District",
    city: "Hyderabad",
    area: "Gachibowli",
    bedrooms: 4,
    bathrooms: 4,
    balconies: 3,
    carpetArea: 2450,
    facing: "North-East",
    floor: 15,
    totalFloors: 25,
    ageYears: 1,
    furnishing: "Unfurnished",
    amenities: ["Clubhouse", "Tennis Court", "Swimming Pool", "Yoga Deck", "EV Charging", "Concierge"],
    nearbySchools: [
      { name: "Oakridge International School", distance: "2.2 km" },
      { name: "Chirec International", distance: "3.8 km" },
    ],
    nearbyColleges: [
      { name: "IIIT Hyderabad", distance: "4.0 km" },
      { name: "University of Hyderabad", distance: "6.5 km" },
    ],
    nearbyHospitals: [
      { name: "AIG Hospitals", distance: "3.1 km" },
      { name: "Continental Hospitals", distance: "2.7 km" },
    ],
    nearbyTransport: [
      { name: "Raidurg Metro", distance: "2.9 km" },
      { name: "Gachibowli Bus Station", distance: "1.5 km" },
      { name: "RGIA Airport", distance: "28 km" },
    ],
    images: [imgs.lounge, imgs.bright, imgs.cozy, imgs.clean],
    status: "available",
    featured: false,
    listedAt: "2026-09-01T14:00:00.000Z",
    updatedAt: "2026-09-15T16:00:00.000Z",
  },
  {
    id: "flat-015",
    title: "Palm Court — Compact 1 BHK Starter Home",
    description:
      "Smartly designed 1 BHK for first-time buyers near Hinjewadi connectivity.",
    price: 4200000,
    location: "Wakad Road",
    city: "Pune",
    area: "Wakad",
    bedrooms: 1,
    bathrooms: 1,
    balconies: 1,
    carpetArea: 520,
    facing: "West",
    floor: 4,
    totalFloors: 11,
    ageYears: 3,
    furnishing: "Semi-Furnished",
    amenities: ["Gym", "Lift", "Security", "Power Backup", "Parking"],
    nearbySchools: [
      { name: "Indira National School", distance: "1.6 km" },
      { name: "Balaji School", distance: "2.3 km" },
    ],
    nearbyColleges: [
      { name: "PCCOE", distance: "3.0 km" },
      { name: "Symbiosis Institute", distance: "5.4 km" },
    ],
    nearbyHospitals: [
      { name: "Aditya Birla Hospital", distance: "4.2 km" },
      { name: "Lifepoint Multispecialty", distance: "2.8 km" },
    ],
    nearbyTransport: [
      { name: "Wakad Bus Stop", distance: "0.4 km" },
      { name: "Hinjewadi IT Park", distance: "3.5 km" },
      { name: "Pune Airport", distance: "22 km" },
    ],
    images: [imgs.studio, imgs.open, imgs.warm],
    status: "available",
    featured: false,
    listedAt: "2026-06-18T08:00:00.000Z",
    updatedAt: "2026-08-28T09:00:00.000Z",
  },
];

export const AMENITY_OPTIONS = [
  "Clubhouse",
  "Swimming Pool",
  "Gym",
  "Children's Play Area",
  "24/7 Security",
  "Power Backup",
  "Covered Parking",
  "Landscaped Garden",
  "Jogging Track",
  "Indoor Games",
  "Visitor Parking",
  "CCTV",
  "Rainwater Harvesting",
  "Tennis Court",
  "Yoga Deck",
  "EV Charging",
  "Smart Home Ready",
  "Concierge",
  "Banquet Hall",
  "Lift",
  "Solar Water Heating",
  "Spa",
  "Cricket Pitch",
  "Amphitheatre",
  "High-Speed Elevators",
  "Retail Plaza",
  "Basketball Court",
  "Shopping Arcade",
  "Community Hall",
  "Water Softener",
  "Intercom",
  "Sewage Treatment",
  "Garden",
  "Pool",
  "Parking",
  "Security",
];

export const FACING_OPTIONS = [
  "North",
  "South",
  "East",
  "West",
  "North-East",
  "North-West",
  "South-East",
  "South-West",
] as const;

export { CITY_OPTIONS } from "./locations";

export const DEFAULT_IMAGES = [imgs.living, imgs.kitchen, imgs.bedroom];

export const ADMIN_CREDENTIALS = {
  username: "admin",
  password: "admin123",
};
